import React, { useRef } from 'react';
import { useReactToPrint } from 'react-to-print';
import { Printer } from 'lucide-react';

interface PrintableReportProps {
  data: any;
  type: 'audit' | 'checklist';
}

// Separate component for printing
const PrintableContent = React.forwardRef<HTMLDivElement, PrintableReportProps>(({ data, type }, ref) => {
  return (
    <div ref={ref} className="p-12 font-sans bg-white text-black min-h-screen">
      {/* Header */}
      <div className="border-b-4 border-black pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-4xl font-black uppercase tracking-tighter mb-2">
            {type === 'audit' ? 'Safety Audit Report' : 'Checklist Log'}
          </h1>
          <p className="text-gray-500 font-mono text-sm uppercase tracking-widest">ComplianceDaddy System Record</p>
        </div>
        <div className="text-right">
          <p className="text-3xl font-bold">{new Date().toLocaleDateString()}</p>
          <p className="text-sm text-gray-500">{new Date().toLocaleTimeString()}</p>
        </div>
      </div>

      {/* Meta Info Grid */}
      <div className="grid grid-cols-2 gap-8 mb-12 p-6 bg-gray-50 rounded-xl border border-gray-200">
        <div>
          <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Venue Location</h3>
          <p className="text-xl font-medium">{data.location || 'Main Venue'}</p>
        </div>
        <div>
          <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Conducted By</h3>
          <p className="text-xl font-medium">{data.user || 'Staff Member'}</p>
        </div>
        <div>
          <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Report ID</h3>
          <p className="font-mono text-gray-600">{data.id || `RPT-${Math.floor(Math.random()*10000)}`}</p>
        </div>
        <div>
          <h3 className="text-xs font-bold text-gray-400 uppercase tracking-wider mb-1">Overall Status</h3>
          <span className={`inline-flex items-center px-3 py-1 rounded-full text-sm font-bold uppercase tracking-wide ${
            data.status === 'pass' ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
          }`}>
            {data.status || 'Completed'}
          </span>
        </div>
      </div>

      {/* Items Table */}
      <table className="w-full mb-8 border-collapse">
        <thead>
          <tr className="border-b-2 border-black">
            <th className="text-left py-3 font-bold uppercase text-sm tracking-wider w-1/2">Item / Checkpoint</th>
            <th className="text-center py-3 font-bold uppercase text-sm tracking-wider w-1/4">Status</th>
            <th className="text-left py-3 font-bold uppercase text-sm tracking-wider w-1/4">Notes / Comments</th>
          </tr>
        </thead>
        <tbody className="divide-y divide-gray-200">
          {data.items?.map((item: any, idx: number) => (
            <tr key={idx} className={idx % 2 === 0 ? 'bg-white' : 'bg-gray-50'}>
              <td className="py-4 pl-4 font-medium text-gray-900">{item.label || item.question || `Item ${idx + 1}`}</td>
              <td className="py-4 text-center">
                <span className={`inline-flex px-2 py-1 rounded text-xs font-bold uppercase ${
                  item.status === 'pass' || item.checked ? 'bg-green-100 text-green-800' : 
                  item.status === 'fail' ? 'bg-red-100 text-red-800' : 'bg-gray-100 text-gray-600'
                }`}>
                  {item.status === 'pass' ? 'PASS' : item.status === 'fail' ? 'FAIL' : item.checked ? 'COMPLETED' : 'N/A'}
                </span>
              </td>
              <td className="py-4 pr-4 text-sm text-gray-500 italic">{item.notes || '-'}</td>
            </tr>
          ))}
        </tbody>
      </table>

      {/* Footer */}
      <div className="fixed bottom-0 left-0 right-0 p-12 border-t border-gray-200 text-center text-xs text-gray-400 bg-white">
        <p>Generated by ComplianceDaddy • {new Date().getFullYear()}</p>
      </div>
    </div>
  );
});

export const ReportPrinter = ({ data, type }: { data: any, type: 'audit' | 'checklist' }) => {
  const componentRef = useRef<HTMLDivElement>(null);
  
  const handlePrint = useReactToPrint({
    contentRef: componentRef,
    documentTitle: `${type}-report-${new Date().toISOString().split('T')[0]}`,
  });

  return (
    <>
      <div style={{ display: 'none' }}>
        <PrintableContent ref={componentRef} data={data} type={type} />
      </div>
      <button
        onClick={() => handlePrint()}
        className="flex items-center px-4 py-2 bg-white border border-gray-300 hover:bg-gray-50 text-gray-700 rounded-lg transition-all shadow-sm font-medium text-sm group"
      >
        <Printer size={16} className="mr-2 group-hover:text-blue-600 transition-colors" />
        Print Report
      </button>
    </>
  );
};
